### PR TITLE
Fixed shorted UART and went through DRC

### PR DESCRIPTION
**Pull request by Duckle29**
Hi there.

I'm about to order boards for this, and decided to go through and add some test-points to the 4 un-used GPIO. I decided to run a quick DRC and clean up some of the kicad-confusion related DRC errors. I however also found this:   
image

Where UART2 TX and RX go right through the I2C debug headers 3v3 pad.
I moved them to sneak between the middle of these pins to avoid getting too close to the coil. 

I also swapped the two inner layers so the ground plane is closer to all the active ICs. Should help a bit with EMC / bypassing, but if there's a reason to reference the 3v3 power plane instead this is the wrong move.

Thanks for a cool project. I'm looking forward to playing with it :) 

Testpoints:  
image
image

### CODE REVIEW

**Comment by spoter368** [comment]
Thanks for the additions! I ran DRC myself but somehow missed those errors in the sea of other issues. You can also probably tell I haven't used UART on my mouse, I used it on the first revision for bringup, but haven't tested it since I got USB working and rev'd the hardware.

I am totally onboard to approve this PR, but would like some sort of validation that these changes don't break existing functionality. If you order your version and they work, post any evidence here and I'll be glad to merge!

**Comment by Duckle29** [comment]
Cool, will do :smiley:

**Comment by a-b** [comment]
Any updates? 
I am happy to help with testing and verification.

@Duckle29, can I piggyback on your PCB order?

**Comment by spoter368** [comment]
After realizing how many people are making these, I went ahead and fixed the shorted UART in the master branch. I haven’t verified the fix, but I wanted to make sure anyone else who’s making these has a decent chance of UART working.

**Comment by Duckle29** [comment]
> After realizing how many people are making these, I went ahead and fixed the shorted UART in the master branch. I haven’t verified the fix, but I wanted to make sure anyone else who’s making these has a decent chance of UART working.

In that case, are you still interested in a PR with the 4 test points? and layer swaps? 

@a-b I may have a spare PCB, but only if things go smoothly. I'll let you know when I know, but depending on where you are I think you're better off getting an order yourself. It'll be a while before I get around to my boards.

**Comment by spoter368** [comment]
I would rather just use this PR and overwrite master once you validate yours, that way master contains a validated PCB. Thoughts?

**Comment by a-b** [comment]
I'm new to PCB design and wondering if it's possible to simulate and test the PCB using software within GitHub actions workflow.

**Comment by hotsgit** [comment]
I guess I ordered the old version, but cutting traces in 4 spots and bodging on some UART wires (if necessary) isn't the worst. Glad I found this post and it's well explained for a relative novice.

**Comment by Duckle29** [comment]
I've received the boards. As mentioned in https://github.com/spoter368/os3m-firmware/issues/4 I noticed https://github.com/spoter368/os3m-hardware/issues/9 and added a default-shorted solder jumper to ground on the back:
image

Boards program over DFU and seem to connect correctly. I just need to have a successful printed flexture (which I think I do) and assemble it :)

**Comment by Duckle29** [comment]
Just read through other issues / pr and saw https://github.com/spoter368/os3m-hardware/issues/10.

That's doing a lot more stuff. Should we close this issue as it seems things have been included there? :)

**Comment by spoter368** [comment]
I think I've got the master board in a pretty good state. No major bugs or features missing. Unless people feel strongly I should implement an overhaul, I think I'll leave it as-is. Closing this PR for now, but I wish you all the best with your version of the board!

**Pull request closed without merging**
